CREATE TABLE IF NOT EXISTS ritvik_modules (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  name       VARCHAR(255) NOT NULL,
  data       LONGTEXT     NOT NULL,
  updated_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);